[project]
name = "rm_dup_lines"
version = "0.1.0"
authors=[{name = "Ana", email="ana@gmail.com"}]
description=""" """
license={text= "MIT"}
dependencies=["jjcli"]

[project.scripts]
rl= "rm_dup_lines:main"
